name: ap
region: tor
services:
  - name: apexpensetrackerbackend2
    source_dir: /
    github:
      repo: arjungautam1/APExpenseTrackerBackend
      branch: main
      deploy_on_push: true
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 8080
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: MONGODB_URI
        scope: RUN_AND_BUILD_TIME
        value: ${MONGODB_URI}
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8080"
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${JWT_SECRET}
      - key: JWT_EXPIRE
        scope: RUN_AND_BUILD_TIME
        value: 7d
      - key: JWT_REFRESH_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${JWT_REFRESH_SECRET}
      - key: JWT_REFRESH_EXPIRE
        scope: RUN_AND_BUILD_TIME
        value: 30d
      - key: CLIENT_URL
        scope: RUN_AND_BUILD_TIME
        value: https://smartexpenseai.com
      - key: GROQ_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${GROQ_API_KEY}
      - key: GROQ_TEXT
        scope: RUN_AND_BUILD_TIME
        value: ${GROQ_TEXT}

  - name: apfront
    source_dir: /
    github:
      repo: arjungautam1/APExpenseTrackerFrontend
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 8080
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: https://smartexpenseai.com/apexpensetrackerbackend2/api
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8080"

domains:
  - domain: smartexpenseai.com
    type: PRIMARY

ingress:
  rules:
    - component:
        name: apexpensetrackerbackend2
      match:
        authority:
          exact: ""
        path:
          prefix: /apexpensetrackerbackend2
    - component:
        name: apfront
      match:
        authority:
          exact: ""
        path:
          prefix: /
