name: apexpensetracker-frontend
static_sites:
  - name: frontend
    source_dir: /
    github:
      repo: arjungautam1/APExpenseTrackerFrontend
      branch: main
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: https://apexpensetracker-fpnq5.ondigitalocean.app/apexpensetrackerbackend2/api
