name: apexpensetracker
services:
  - name: backend
    source_dir: /
    github:
      repo: arjungautam1/APExpenseTrackerBackend
      branch: main
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: GROQ_API_KEY
        value: ${GROQ_API_KEY}
      - key: GROQ_TEXT
        value: ${GROQ_TEXT}
      - key: JWT_SECRET
        value: ${JWT_SECRET}

static_sites:
  - name: frontend
    source_dir: /
    github:
      repo: arjungautam1/APExpenseTrackerFrontend
      branch: main
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: https://apexpensetracker-fpnq5.ondigitalocean.app/api
