name: apexpensetracker
region: tor
services:
  - name: backend
    source_dir: /
    github:
      repo: arjungautam1/APExpenseTrackerBackend
      branch: main
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: MONGODB_URI
        scope: RUN_AND_BUILD_TIME
        value: ${MONGODB_URI}
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8080"
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${JWT_SECRET}
      - key: JWT_EXPIRE
        scope: RUN_AND_BUILD_TIME
        value: 7d
      - key: JWT_REFRESH_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${JWT_REFRESH_SECRET}
      - key: JWT_REFRESH_EXPIRE
        scope: RUN_AND_BUILD_TIME
        value: 30d
      - key: CLIENT_URL
        scope: RUN_AND_BUILD_TIME
        value: https://ap-bhaoh.ondigitalocean.app
      - key: GROQ_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${GROQ_API_KEY}
      - key: GROQ_TEXT
        scope: RUN_AND_BUILD_TIME
        value: ${GROQ_TEXT}

static_sites:
  - name: frontend
    source_dir: /
    github:
      repo: arjungautam1/APExpenseTrackerFrontend
      branch: main
    build_command: npm install && npm run build
    output_dir: dist
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: https://ap-bhaoh.ondigitalocean.app/apexpensetrackerbackend2/api

ingress:
  rules:
    - component:
        name: backend
      match:
        path:
          prefix: /api
    - component:
        name: frontend
      match:
        path:
          prefix: /
