name: apexpensetracker-frontend
services:
  - name: frontend
    source_dir: /
    github:
      repo: arjungautam1/APExpenseTrackerFrontend
      branch: main
    build_command: npm install && npm run build
    run_command: npm run preview
    environment_slug: html
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: https://apexpensetracker-fpnq5.ondigitalocean.app/apexpensetrackerbackend2/api
